project:
  type: book


book:
  title: "Meine Geschichte"
  subtitle: "Die Reise nach Amerika und wieder zurück"
  author: Hilda Seematter
  chapters:
    - index.qmd
    - 1-kapitel.qmd    
    - 2-kapitel.qmd
    - 3-kapitel.qmd
    - 4-kapitel.qmd
    - 5-kapitel.qmd
    - "---"
    - impressum.qmd

format: 
  html:
    css: style.css
    email-obfuscation: javascript

lang: de
language: 
  de: 
    title-block-author-single: "Authorin"
    crossref-fig-title: "Foto"
toc: false
number-sections: false
crossref:
  chapters: false
  